/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  Deck as RevealDeck
} from './components/deck/deck';

declare global {
  interface HTMLRevealDeckElement extends RevealDeck, HTMLElement {
  }
  var HTMLRevealDeckElement: {
    prototype: HTMLRevealDeckElement;
    new (): HTMLRevealDeckElement;
  };
  interface HTMLElementTagNameMap {
    "reveal-deck": HTMLRevealDeckElement;
  }
  interface ElementTagNameMap {
    "reveal-deck": HTMLRevealDeckElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "reveal-deck": JSXElements.RevealDeckAttributes;
    }
  }
  namespace JSXElements {
    export interface RevealDeckAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  Slide as RevealSlide
} from './components/slide/slide';

declare global {
  interface HTMLRevealSlideElement extends RevealSlide, HTMLElement {
  }
  var HTMLRevealSlideElement: {
    prototype: HTMLRevealSlideElement;
    new (): HTMLRevealSlideElement;
  };
  interface HTMLElementTagNameMap {
    "reveal-slide": HTMLRevealSlideElement;
  }
  interface ElementTagNameMap {
    "reveal-slide": HTMLRevealSlideElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "reveal-slide": JSXElements.RevealSlideAttributes;
    }
  }
  namespace JSXElements {
    export interface RevealSlideAttributes extends HTMLAttributes {
      active?: boolean;
      backgroundColor?: string;
      backgroundImage?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
